apiVersion: v1
kind: ConfigMap
metadata:
  name: dj-demo-crm-conf
data:
  # https://www.mongodb.com/docs/manual/reference/connection-string/#connection-string-uri-format
  MONGODB_URI: "mongodb://root_user:MySp3c1alP%40ssW0rd%21@dj-mongo-mongodb-0.dj-mongo-mongodb-headless.davidjohn.svc.cluster.local:27017,dj-mongo-mongodb-1.dj-mongo-mongodb-headless.davidjohn.svc.cluster.local:27017,dj-mongo-mongodb-2.dj-mongo-mongodb-headless.davidjohn.svc.cluster.local:27017/?replicaSet=rs0"
  # "mongodb-0.mongodb.davidjohn.svc.cluster.local"
  LOG_LEVEL: "info"
  PERSISTENCE: "true"

