global:
  rbac:
    create: false
grafana:
  rbac:
    create: false
kube-state-metrics:
  rbac:
    create: false

kubernetesServiceMonitors:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: false

