apiVersion: v1
kind: ConfigMap
metadata:
  name: dj-demo-crm-conf
data:
  # https://www.mongodb.com/docs/manual/reference/connection-string/#connection-string-uri-format
  MONGODB_URI: "mongodb://mongodb-0.mongodb-service,mongodb-1.mongodb-service,mongodb-2-service/?replicaSet=rs0"
  # "mongodb-0.mongodb.davidjohn.svc.cluster.local"
  LOG_LEVEL: "info"
  PERSISTENCE: "true"

